version: "3"

services:
  postgres-1:
    container_name: db1
    image: postgres:14.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pw}
      POSTGRES_DB: my-db
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /postgres/data/
    volumes:
      - ./postgres_db1:/postgres/data/
    ports:
      - "5431:5432"

  postgres-2:
    container_name: db2
    image: postgres:14.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pw}
      POSTGRES_DB: my-db
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /postgres/data/
    volumes:
      - ./postgres_db2:/postgres/data/
    ports:
      - "5432:5432"
